#include "VKCallbackApiHandler.hpp"

const std::string VKCallbackApiHandler::AUDIO_NEW = "audio_new";
const std::string VKCallbackApiHandler::BOARD_POST_NEW = "board_post_new";
const std::string VKCallbackApiHandler::BOARD_POST_EDIT = "board_post_edit";
const std::string VKCallbackApiHandler::BOARD_POST_RESTORE = "board_post_restore";
const std::string VKCallbackApiHandler::BOARD_POST_DELETE = "board_post_delete";
const std::string VKCallbackApiHandler::CONFIRMATION = "confirmation";
const std::string VKCallbackApiHandler::GROUP_LEAVE = "group_leave";
const std::string VKCallbackApiHandler::GROUP_JOIN = "group_join";
const std::string VKCallbackApiHandler::GROUP_CHANGE_PHOTO = "group_change_photo";
const std::string VKCallbackApiHandler::GROUP_CHANGE_SETTINGS = "group_change_settings";
const std::string VKCallbackApiHandler::GROUP_OFFICERS_EDIT = "group_officers_edit";
const std::string VKCallbackApiHandler::LEAD_FORMS_NEW = "lead_forms_new";
const std::string VKCallbackApiHandler::MARKET_COMMENT_NEW = "market_comment_new";
const std::string VKCallbackApiHandler::MARKET_COMMENT_DELETE = "market_comment_delete";
const std::string VKCallbackApiHandler::MARKET_COMMENT_EDIT = "market_comment_edit";
const std::string VKCallbackApiHandler::MARKET_COMMENT_RESTORE = "market_comment_restore";
const std::string VKCallbackApiHandler::MARKET_ORDER_NEW = "market_order_new";
const std::string VKCallbackApiHandler::MARKET_ORDER_EDIT = "market_order_edit";
const std::string VKCallbackApiHandler::MESSAGE_NEW = "message_new";
const std::string VKCallbackApiHandler::MESSAGE_REPLY = "message_reply";
const std::string VKCallbackApiHandler::MESSAGE_EDIT = "message_edit";
const std::string VKCallbackApiHandler::MESSAGE_ALLOW = "message_allow";
const std::string VKCallbackApiHandler::MESSAGE_DENY = "message_deny";
const std::string VKCallbackApiHandler::MESSAGE_READ = "message_read";
const std::string VKCallbackApiHandler::MESSAGE_TYPING_STATE = "message_typing_state";
const std::string VKCallbackApiHandler::MESSAGES_EDIT = "messages_edit";
const std::string VKCallbackApiHandler::MESSAGE_REACTION_EVENT = "message_reaction_event";
const std::string VKCallbackApiHandler::PHOTO_NEW = "photo_new";
const std::string VKCallbackApiHandler::PHOTO_COMMENT_NEW = "photo_comment_new";
const std::string VKCallbackApiHandler::PHOTO_COMMENT_DELETE = "photo_comment_delete";
const std::string VKCallbackApiHandler::PHOTO_COMMENT_EDIT = "photo_comment_edit";
const std::string VKCallbackApiHandler::PHOTO_COMMENT_RESTORE = "photo_comment_restore";
const std::string VKCallbackApiHandler::POLL_VOTE_NEW = "poll_vote_new";
const std::string VKCallbackApiHandler::USER_BLOCK = "user_block";
const std::string VKCallbackApiHandler::USER_UNBLOCK = "user_unblock";
const std::string VKCallbackApiHandler::VIDEO_NEW = "video_new";
const std::string VKCallbackApiHandler::VIDEO_COMMENT_NEW = "video_comment_new";
const std::string VKCallbackApiHandler::VIDEO_COMMENT_DELETE = "video_comment_delete";
const std::string VKCallbackApiHandler::VIDEO_COMMENT_EDIT = "video_comment_edit";
const std::string VKCallbackApiHandler::VIDEO_COMMENT_RESTORE = "video_comment_restore";
const std::string VKCallbackApiHandler::WALL_POST_NEW = "wall_post_new";
const std::string VKCallbackApiHandler::WALL_REPLY_NEW = "wall_reply_new";
const std::string VKCallbackApiHandler::WALL_REPLY_EDIT = "wall_reply_edit";
const std::string VKCallbackApiHandler::WALL_REPLY_DELETE = "wall_reply_delete";
const std::string VKCallbackApiHandler::WALL_REPLY_RESTORE = "wall_reply_restore";
const std::string VKCallbackApiHandler::WALL_REPOST = "wall_repost";
const std::string VKCallbackApiHandler::WALL_SCHEDULE_POST_NEW = "wall_schedule_post_new";
const std::string VKCallbackApiHandler::WALL_SCHEDULE_POST_DELETE = "wall_schedule_post_delete";

void VKCallbackApiHandler::parseObject(int group_id, const std::string* secret, const std::string& type, const nlohmann::json& object) {
    if (type == AUDIO_NEW) audioNew(group_id, secret, object);
    else if (type == BOARD_POST_NEW) boardPostNew(group_id, secret, object);
    else if (type == BOARD_POST_EDIT) boardPostEdit(group_id, secret, object);
    else if (type == BOARD_POST_RESTORE) boardPostRestore(group_id, secret, object);
    else if (type == BOARD_POST_DELETE) boardPostDelete(group_id, secret, object);
    else if (type == CONFIRMATION) confirmation(group_id, secret, object);
    else if (type == GROUP_LEAVE) groupLeave(group_id, secret, object);
    else if (type == GROUP_JOIN) groupJoin(group_id, secret, object);
    else if (type == GROUP_CHANGE_PHOTO) groupChangePhoto(group_id, secret, object);
    else if (type == GROUP_CHANGE_SETTINGS) groupChangeSettings(group_id, secret, object);
    else if (type == GROUP_OFFICERS_EDIT) groupOfficersEdit(group_id, secret, object);
    else if (type == LEAD_FORMS_NEW) leadFormsNew(group_id, secret, object);
    else if (type == MARKET_COMMENT_NEW) marketCommentNew(group_id, secret, object);
    else if (type == MARKET_COMMENT_DELETE) marketCommentDelete(group_id, secret, object);
    else if (type == MARKET_COMMENT_EDIT) marketCommentEdit(group_id, secret, object);
    else if (type == MARKET_COMMENT_RESTORE) marketCommentRestore(group_id, secret, object);
    else if (type == MARKET_ORDER_NEW) marketOrderNew(group_id, secret, object);
    else if (type == MARKET_ORDER_EDIT) marketOrderEdit(group_id, secret, object);
    else if (type == MESSAGE_NEW) messageNew(group_id, secret, object);
    else if (type == MESSAGE_REPLY) messageReply(group_id, secret, object);
    else if (type == MESSAGE_EDIT) messageEdit(group_id, secret, object);
    else if (type == MESSAGE_ALLOW) messageAllow(group_id, secret, object);
    else if (type == MESSAGE_DENY) messageDeny(group_id, secret, object);
    else if (type == MESSAGE_READ) messageRead(group_id, secret, object);
    else if (type == MESSAGE_TYPING_STATE) messageTypingState(group_id, secret, object);
    else if (type == MESSAGES_EDIT) messagesEdit(group_id, secret, object);
    else if (type == MESSAGE_REACTION_EVENT) messageReactionEvent(group_id, secret, object);
    else if (type == PHOTO_NEW) photoNew(group_id, secret, object);
    else if (type == PHOTO_COMMENT_NEW) photoCommentNew(group_id, secret, object);
    else if (type == PHOTO_COMMENT_DELETE) photoCommentDelete(group_id, secret, object);
    else if (type == PHOTO_COMMENT_EDIT) photoCommentEdit(group_id, secret, object);
    else if (type == PHOTO_COMMENT_RESTORE) photoCommentRestore(group_id, secret, object);
    else if (type == POLL_VOTE_NEW) pollVoteNew(group_id, secret, object);
    else if (type == USER_BLOCK) userBlock(group_id, secret, object);
    else if (type == USER_UNBLOCK) userUnblock(group_id, secret, object);
    else if (type == VIDEO_NEW) videoNew(group_id, secret, object);
    else if (type == VIDEO_COMMENT_NEW) videoCommentNew(group_id, secret, object);
    else if (type == VIDEO_COMMENT_DELETE) videoCommentDelete(group_id, secret, object);
    else if (type == VIDEO_COMMENT_EDIT) videoCommentEdit(group_id, secret, object);
    else if (type == VIDEO_COMMENT_RESTORE) videoCommentRestore(group_id, secret, object);
    else if (type == WALL_POST_NEW) wallPostNew(group_id, secret, object);
    else if (type == WALL_REPLY_NEW) wallReplyNew(group_id, secret, object);
    else if (type == WALL_REPLY_EDIT) wallReplyEdit(group_id, secret, object);
    else if (type == WALL_REPLY_DELETE) wallReplyDelete(group_id, secret, object);
    else if (type == WALL_REPLY_RESTORE) wallReplyRestore(group_id, secret, object);
    else if (type == WALL_REPOST) wallRepost(group_id, secret, object);
    else if (type == WALL_SCHEDULE_POST_NEW) wallSchedulePostNew(group_id, secret, object);
    else if (type == WALL_SCHEDULE_POST_DELETE) wallSchedulePostDelete(group_id, secret, object);
}